DROP USER IF EXISTS heat;
DROP DATABASE IF EXISTS heat;

CREATE DATABASE heat;
CREATE USER heat WITH ENCRYPTED PASSWORD 'H3@tF33t';

GRANT ALL PRIVILEGES ON DATABASE heat TO heat;
ALTER DATABASE heat OWNER TO heat;
